tasks:
  - name: Setup Classify API requirements
    init: |
      git remote add ${GITHUB_USER} https://github.com/${GITHUB_USER}/ap-labs.git
      git config --local classify.github-user "${GITHUB_USER}"
      git config --local classify.token ${CLASSIFY_TOKEN}
    
    
